normalize_terms = {
    'democratic party': 'democratic_party',
    'left wing': 'leftwing',
    'right wing': 'rightwing',
    'african american': 'african_american',
    'african americans': 'african_american',
    'native american': 'native_american',
    'native americans': 'native_american',
    'asian american': 'asian_american',
    'asian americans': 'asian_american',
    'pacific islander': 'pacific_islander',
    'pacific islanders': 'pacific_islander',
    'illegal alien': 'illegal_alien',
    'illegal aliens': 'illegal_alien',
    'did not graduate': 'did_not_graduate',
    'high school graduate': 'high_school_graduate',
    'did not go to college': 'did_not_go_to_college',
    'lower class': 'lowerclass',
    'low socioeconomic status': 'low_socioeconomic_status',
    'upper class': 'upperclass',
    'middle class': 'middle_class',
    'one percent': 'one_percent',
    '1%': 'one_percent',
    'gun owners': 'gun_owners',
    'second amendment advocates': 'second_amendment_advocates',
    'anti-gun advocates': 'antigun_advocates',
    'antigun advocates': 'antigun_advocates',
    'north korea': 'north_korea',
    'donald trump': 'donald_trump',
    'bernie sanders': 'bernie_sanders',
    'samantha bee': 'samantha_bee',
    'megyn kelly': 'megyn_kelly',
    'hillary clinton': 'hillary_clinton',
    'de blasio': 'de_blasio',
    'rod rosenstein': 'rod_rosenstein',
    'ruth bader ginsberg': 'ruth_bader_ginsberg',
    'justice ginsberg': 'justice_ginsberg',
    'maggie haberman': 'maggie_haberman',
    'bill clinton': 'bill_clinton',
    'don lemon': 'don_lemon',
    'jimmy kimmel': 'jimmy_kimmel',
    'vice president': 'vice_president',
    'di nero': 'di_nero',
    'bill maher': 'bill_maher',
    'dont believe': 'dont_believe',
    'beyond parody': 'beyond_parody',
    'big cheese': 'big_cheese',
    'come after': 'come_after',
    'couldnt qualify': 'couldnt_qualify',
    'dancing on graves': 'dancing_on_graves',
    'denial of freedom': 'denial_of_freedom',
    'devil worshipers': 'devil_worshipers',
    'lap dog': 'lap_dog',
    'dont understand': 'dont_understand',
    'drive by': 'drive_by',
    'going by the boards': 'going_by_the_boards',
    'group think': 'group_think',
    'having a fit': 'having_a_fit',
    'humpty dumpty': 'humpty_dumpty',
    'not logical': 'not_logical',
    'not honest': 'not_honest',
    'not protecting': 'not_protecting',
    'not tolerant': 'not_tolerant',
    'say anything they want': 'say_anything_they_want',
    'scum of the earth': 'scum_of_the_earth',
    'tiger mom': 'tiger_mom',
    'witch hunt': 'witch_hunt',
    'young skulls full of mush': 'young_skulls_full_of_mush',

}